spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:mysql://localhost:3306/transaction_test
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
  # jOOQ
  jooq:
    sql-dialect: MYSQL