spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:mysql://localhost:3306/transaction_test
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
  # jOOQ
  jooq:
    sql-dialect: MYSQL
logging:
  level:
    root: DEBUG
