/*
 * This file is generated by jOOQ.
 */
package com.transaction.demo.db.transaction;


import com.transaction.demo.db.transaction.tables.User;


/**
 * Convenience access to all tables in transaction_test
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>transaction_test.user</code>.
     */
    public static final User USER = User.USER;
}
