/*
 * This file is generated by jOOQ.
 */
package com.transaction.demo.db.transaction;


import com.transaction.demo.db.transaction.tables.DeliveryProgress;
import com.transaction.demo.db.transaction.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionTest extends SchemaImpl {

    private static final long serialVersionUID = -1021767191;

    /**
     * The reference instance of <code>transaction_test</code>
     */
    public static final TransactionTest TRANSACTION_TEST = new TransactionTest();

    /**
     * The table <code>transaction_test.delivery_progress</code>.
     */
    public final DeliveryProgress DELIVERY_PROGRESS = DeliveryProgress.DELIVERY_PROGRESS;

    /**
     * The table <code>transaction_test.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private TransactionTest() {
        super("transaction_test", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            DeliveryProgress.DELIVERY_PROGRESS,
            User.USER);
    }
}
